### ISSUE TITLE
ReadMeに付けた各言語ファイルへの相互リンクがうまく動きません

### ISSUE THREAD

**Issue by haya-sann** [INTER-Mediator/IMApp_Trial#2]
日本語のReadMeを作りました。それぞれのファイルを相互参照できるようにしたいのですが、なぜか日本語版に付けた［英語版へのリンク］しか動きません。URLは正しいように思えますが・・・
なんで？
[日本語版はこちらにあります](https://github.com/inter-mediator/IMApp_Trial/blob/master/README-ja.md)
[English README is here](https://github.com/inter-mediator/IMApp_Trial/blob/master/README.md)

**Comment by haya-sann** [comment]
リンク先のファイル名が間違っていました。
正しくは
[日本語版はこちらにあります](https://github.com/inter-mediator/IMApp_Trial/blob/master/README-jp.md)
でした。

**Comment by msyk** [comment]
もしかして、Pull Req.が受けれた後の状態じゃないと、リンクが正しくないのかもしれません。とりあえず受け入れて、後から考えるでもいいかと思います。
